export const mockProperties = [
  { id: 1, dealType: 'Аренда', rentPeriod: 'Помесячно', city: 'Астана', type: 'Квартира', rooms: 2, area: 45, floor: 12, totalFloors: 12, price: 200000, owner: false, authorType: 'Компания', photo: true, photoCount: 13, furnished: 'Да', withPets: false, withKids: true, address: 'Сарыарка р-н, Чингиз Айтматов 79', complex: 'ЖК Alakol', description: 'Сдам евро двушку. Квартира свободна, заселение сразу. Шикарный вид на город, развитая инфраструктура. Рядом школы, садики, магазины.', date: '31 мар.', views: 539, isHot: true, img: 'https://images.unsplash.com/photo-1502672260266-1c1de2d9200b?auto=format&fit=crop&w=800&q=80' },
  { id: 2, dealType: 'Аренда', rentPeriod: 'Помесячно', city: 'Алматы', type: 'Квартира', rooms: 1, area: 35, floor: 4, totalFloors: 9, price: 180000, owner: true, authorType: 'Хозяин', photo: true, photoCount: 8, furnished: 'Да', withPets: true, withKids: true, address: 'Бостандыкский р-н, Абая 150', complex: 'ЖК Гагарин Парк', description: 'Светлая квартира после свежего косметического ремонта. Имеется вся необходимая бытовая техника (стиралка, холодильник, микроволновка). Можно с небольшими питомцами.', date: '31 мар.', views: 245, isHot: true, img: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80' },
  { id: 3, dealType: 'Продажа', city: 'Астана', type: 'Квартира', rooms: 3, area: 85, floor: 7, totalFloors: 16, price: 35000000, owner: false, authorType: 'Специалист', photo: true, photoCount: 22, furnished: 'Нет', address: 'Есильский р-н, Мангилик Ел 50', complex: 'ЖК Nova City', description: 'Просторная 3-комнатная квартира в ЖК бизнес-класса. Предчистовая отделка, свободная планировка, панорамные окна. Закрытый двор, охрана 24/7. Документы на руках, ипотека рассматривается.', date: '30 мар.', views: 1024, isHot: false, img: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80' },
  { id: 4, dealType: 'Аренда', rentPeriod: 'Посуточно', city: 'Астана', type: 'Квартира', rooms: 2, area: 50, floor: 5, totalFloors: 10, price: 15000, owner: true, authorType: 'Хозяин', photo: true, photoCount: 5, furnished: 'Да', withPets: false, withKids: true, address: 'Алматы р-н, Кудайбердыулы 17', complex: '', description: 'Посуточная аренда квартиры. Всегда чисто, свежее постельное белье и полотенца. Высокоскоростной Wi-Fi, Smart TV. В шаговой доступности супермаркеты и остановки.', date: '31 мар.', views: 112, isHot: true, img: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80' }
];

export const generateTitle = (p) => {
  if (p.type === 'Квартира') return `${p.rooms}-комнатная квартира, ${p.area} м², ${p.floor}/${p.totalFloors} этаж`;
  return `${p.rooms}-комнатный ${p.type.toLowerCase()}, ${p.area} м²`;
};